//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StroitelnayaCompaniyaApp.FailiDannih
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdinicaIzmereniya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EdinicaIzmereniya()
        {
            this.Stroimaterial = new HashSet<Stroimaterial>();
        }
    
        public string Kod { get; set; }
        public string Naimenovaniye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stroimaterial> Stroimaterial { get; set; }
    }
}
